---
apiVersion: v1
kind: Service
metadata:
  name: consul-server-external-udp
spec:
  type: LoadBalancer
  ports:
  - name: serflan-udp
    protocol: UDP
    port: 8301
  - name: consuldns-udp
    protocol: UDP
    port: 53
    targetPort: 8600
  selector:
    app: consul
    release: consul-server
---
apiVersion: v1
kind: Service
metadata:
  name: consul-server-external-tcp
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8500
  - name: rpc
    port: 8400
  - name: serflan-tcp
    protocol: TCP
    port: 8301
  - name: server
    port: 8300
  - name: consuldns-tcp
    port: 8600
  selector:
    app: consul
    release: consul-server