---
# Source: consul/templates/consul-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-server-configuration
  labels:
    app: consul
    chart: consul-7.0.15
    release: consul-server
    heritage: Helm
data:
  config.json:
    |-
      {
        "client_addr": "0.0.0.0",
        "recursors": [
          "8.8.8.8"
        ]
      }
  connection.json: |
    {
      "retry_join": ["consul-server-0.consul-server.demo.svc"]
    }
---
# Source: consul/templates/consul-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: consul-server
  labels:
    app: consul
    chart: consul-7.0.15
    release: consul-server
    heritage: Helm
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 8500
    - name: rpc
      port: 8400
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
    - name: server
      port: 8300
    - name: consuldns-tcp
      port: 8600
    - name: consuldns-udp
      protocol: "UDP"
      port: 8600
  clusterIP: None
  selector:
    app: consul
    release: consul-server
---
# Source: consul/templates/ui-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: consul-server-ui
  labels:
    app: consul
    chart: consul-7.0.15
    release: consul-server
    heritage: Helm
  annotations:
    {}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: consul
    release: consul-server
---
# Source: consul/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul-server
  labels:
    app: consul
    chart: consul-7.0.15
    release: consul-server
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: consul
      release: consul-server
  serviceName: consul-server
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: consul
        chart: consul-7.0.15
        release: consul-server
        heritage: Helm
    spec:      
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
        - name: consul
          image: docker.io/bitnami/consul:1.7.3-debian-10-r1
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 8500
            - name: rpc
              containerPort: 8400
            - name: serflan-tcp
              protocol: "TCP"
              containerPort: 8301
            - name: serflan-udp
              protocol: "UDP"
              containerPort: 8301
            - name: server
              containerPort: 8300
            - name: consuldns-tcp
              containerPort: 8600
            - name: consuldns-udp
              protocol: "UDP"
              containerPort: 8600
          resources:
            limits: {}
            requests: {}
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: CONSUL_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CONSUL_RETRY_JOIN
              value: "consul-server-0.consul-server.demo.svc.cluster.local"
            - name: CONSUL_DISABLE_KEYRING_FILE
              value: "true"
            - name: CONSUL_BOOTSTRAP_EXPECT
              value: "1"
            - name: CONSUL_BOOTSTRAP_EXPECT
              value: "1"
            - name: CONSUL_RAFT_MULTIPLIER
              value: "1"
            - name: CONSUL_DOMAIN
              value: "consul"
            - name: CONSUL_DATACENTER
              value: "dc1"
            - name: CONSUL_UI
              value: "true"
            - name: CONSUL_HTTP_PORT_NUMBER
              value: "8500"
            - name: CONSUL_DNS_PORT_NUMBER
              value: "8600"
            - name: CONSUL_RPC_PORT_NUMBER
              value: "8300"
            - name: CONSUL_SERF_LAN_PORT_NUMBER
              value: "8301"
          livenessProbe:
            exec:
              command:
                - consul
                - operator
                - raft
                - list-peers
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - consul
                - members
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          lifecycle:
            preStop:
              exec:
                command:
                  - consul
                  - leave
          volumeMounts:
            - name: consul-config
              mountPath: /opt/bitnami/consul/conf/config.json
              subPath: config.json
            - name: consul-config
              mountPath: /opt/bitnami/consul/conf/connection.json
              subPath: connection.json
      volumes:
        - name: consul-config
          configMap:
            name: consul-server-configuration
        - name: data
          emptyDir: {}
